# StrafeNPCs 1.0
#
# ==============================================================================
# StrafeNPCs Configuration
# ==============================================================================
#
# Created by zNotHydr0
# Github: https://github.com/zNotHydr0

# Configuration
debug: false